name: exampledataset_optimized_auto
root: ../../exampledataset
format: custom
format_spec: ../format_specs/exampledataset_optimized_auto.yaml
task: classification
splits:
  train: .
image:
  domain: intensity
  channels: 1
label:
  source: filename
  filename_schema: dataset_format_spec
normalization:
  image_mode: link_or_reference
